### PR TITLE
Feature: 회원정보 수정 기능 구현 완료

### LINKED ISSUE #14: Feature: 회원정보 수정 기능 구현
### Feature List

- [ ] one
- [ ] two
- [ ] three

### PR DESCRIPTION
**Pull request by yeonise**
## Key Feature

닉네임 변경 기능과 비밀번호 변경 기능을 구현했습니다.

## To reviewer

- 변경에 성공하면, 변경된 사용자에 대한 정보를 응답하도록 했습니다.
- DTO를 검증하는 방식을 통일하고자 했습니다.
  - 단, 기존 비밀번호가 일치하는지 검증하는 애너테이션은 클래스에 위치합니다. 

Close #14

### CODE REVIEW

**Comment by yeonise** [comment]
### Test Coverage Report
|Overall Project|89.57% **`-0.26%`**|:green_apple:|
|:-|:-|:-:|
|Files changed|98.34%|:green_apple:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[PasswordFormatCheck.java](https://github.com/mujik-tigers/on-and-off/blob/d3f93a46733592ea0dbbb31c1b513a7532f28130/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fvalidator%2Fmember%2FPasswordFormatCheck.java)|100%|:green_apple:|
|[PasswordMatchCheck.java](https://github.com/mujik-tigers/on-and-off/blob/d3f93a46733592ea0dbbb31c1b513a7532f28130/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fvalidator%2Fmember%2FPasswordMatchCheck.java)|100%|:green_apple:|
|[Member.java](https://github.com/mujik-tigers/on-and-off/blob/d3f93a46733592ea0dbbb31c1b513a7532f28130/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2FMember.java)|100%|:green_apple:|
|[ErrorType.java](https://github.com/mujik-tigers/on-and-off/blob/d3f93a46733592ea0dbbb31c1b513a7532f28130/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fexception%2FErrorType.java)|100%|:green_apple:|
|[MemberController.java](https://github.com/mujik-tigers/on-and-off/blob/d3f93a46733592ea0dbbb31c1b513a7532f28130/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fpresentation%2FMemberController.java)|100%|:green_apple:|
|[ResponseMessage.java](https://github.com/mujik-tigers/on-and-off/blob/d3f93a46733592ea0dbbb31c1b513a7532f28130/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Futil%2Fapi%2FResponseMessage.java)|100%|:green_apple:|
|[MemberService.java](https://github.com/mujik-tigers/on-and-off/blob/d3f93a46733592ea0dbbb31c1b513a7532f28130/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fapplication%2FMemberService.java)|100%|:green_apple:|
|[ModifiedMember.java](https://github.com/mujik-tigers/on-and-off/blob/d3f93a46733592ea0dbbb31c1b513a7532f28130/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fdto%2FModifiedMember.java)|100%|:green_apple:|
|[NicknameChangeForm.java](https://github.com/mujik-tigers/on-and-off/blob/d3f93a46733592ea0dbbb31c1b513a7532f28130/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fdto%2FNicknameChangeForm.java)|100%|:green_apple:|
|[ValidPasswordChangeForm.java](https://github.com/mujik-tigers/on-and-off/blob/d3f93a46733592ea0dbbb31c1b513a7532f28130/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fdto%2FValidPasswordChangeForm.java)|100%|:green_apple:|
|[PasswordChangeForm.java](https://github.com/mujik-tigers/on-and-off/blob/d3f93a46733592ea0dbbb31c1b513a7532f28130/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fdto%2FPasswordChangeForm.java)|100%|:green_apple:|
|[UniqueNicknameChangeForm.java](https://github.com/mujik-tigers/on-and-off/blob/d3f93a46733592ea0dbbb31c1b513a7532f28130/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fdto%2FUniqueNicknameChangeForm.java)|100%|:green_apple:|
|[MemberNotFoundException.java](https://github.com/mujik-tigers/on-and-off/blob/d3f93a46733592ea0dbbb31c1b513a7532f28130/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fexception%2Fmember%2FMemberNotFoundException.java)|0%|:x:|

**Comment by yeonise** [comment]
### Test Coverage Report
|Overall Project|89.57% **`-0.26%`**|:green_apple:|
|:-|:-|:-:|
|Files changed|98.34%|:green_apple:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[EmailDuplicateCheck.java](https://github.com/mujik-tigers/on-and-off/blob/c077bc18cf552dfff4c0a1e48a6cea63c88edc36/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fvalidator%2Fmember%2FEmailDuplicateCheck.java)|100%|:green_apple:|
|[NicknameDuplicateCheck.java](https://github.com/mujik-tigers/on-and-off/blob/c077bc18cf552dfff4c0a1e48a6cea63c88edc36/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fvalidator%2Fmember%2FNicknameDuplicateCheck.java)|100%|:green_apple:|
|[EmailFormatCheck.java](https://github.com/mujik-tigers/on-and-off/blob/c077bc18cf552dfff4c0a1e48a6cea63c88edc36/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fvalidator%2Fmember%2FEmailFormatCheck.java)|100%|:green_apple:|
|[PasswordFormatCheck.java](https://github.com/mujik-tigers/on-and-off/blob/c077bc18cf552dfff4c0a1e48a6cea63c88edc36/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fvalidator%2Fmember%2FPasswordFormatCheck.java)|100%|:green_apple:|
|[NicknameFormatCheck.java](https://github.com/mujik-tigers/on-and-off/blob/c077bc18cf552dfff4c0a1e48a6cea63c88edc36/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fvalidator%2Fmember%2FNicknameFormatCheck.java)|100%|:green_apple:|
|[PasswordMatchCheck.java](https://github.com/mujik-tigers/on-and-off/blob/c077bc18cf552dfff4c0a1e48a6cea63c88edc36/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fvalidator%2Fmember%2FPasswordMatchCheck.java)|100%|:green_apple:|
|[Member.java](https://github.com/mujik-tigers/on-and-off/blob/c077bc18cf552dfff4c0a1e48a6cea63c88edc36/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2FMember.java)|100%|:green_apple:|
|[ErrorType.java](https://github.com/mujik-tigers/on-and-off/blob/c077bc18cf552dfff4c0a1e48a6cea63c88edc36/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fexception%2FErrorType.java)|100%|:green_apple:|
|[MemberController.java](https://github.com/mujik-tigers/on-and-off/blob/c077bc18cf552dfff4c0a1e48a6cea63c88edc36/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fpresentation%2FMemberController.java)|100%|:green_apple:|
|[ResponseMessage.java](https://github.com/mujik-tigers/on-and-off/blob/c077bc18cf552dfff4c0a1e48a6cea63c88edc36/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Futil%2Fapi%2FResponseMessage.java)|100%|:green_apple:|
|[MemberService.java](https://github.com/mujik-tigers/on-and-off/blob/c077bc18cf552dfff4c0a1e48a6cea63c88edc36/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fapplication%2FMemberService.java)|100%|:green_apple:|
|[ModifiedMember.java](https://github.com/mujik-tigers/on-and-off/blob/c077bc18cf552dfff4c0a1e48a6cea63c88edc36/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fdto%2FModifiedMember.java)|100%|:green_apple:|
|[NicknameChangeForm.java](https://github.com/mujik-tigers/on-and-off/blob/c077bc18cf552dfff4c0a1e48a6cea63c88edc36/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fdto%2FNicknameChangeForm.java)|100%|:green_apple:|
|[ValidPasswordChangeForm.java](https://github.com/mujik-tigers/on-and-off/blob/c077bc18cf552dfff4c0a1e48a6cea63c88edc36/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fdto%2FValidPasswordChangeForm.java)|100%|:green_apple:|
|[PasswordChangeForm.java](https://github.com/mujik-tigers/on-and-off/blob/c077bc18cf552dfff4c0a1e48a6cea63c88edc36/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fdto%2FPasswordChangeForm.java)|100%|:green_apple:|
|[UniqueNicknameChangeForm.java](https://github.com/mujik-tigers/on-and-off/blob/c077bc18cf552dfff4c0a1e48a6cea63c88edc36/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fdto%2FUniqueNicknameChangeForm.java)|100%|:green_apple:|
|[MemberNotFoundException.java](https://github.com/mujik-tigers/on-and-off/blob/c077bc18cf552dfff4c0a1e48a6cea63c88edc36/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fexception%2Fmember%2FMemberNotFoundException.java)|0%|:x:|

**Comment by ghkdgus29** [comment]
이번 PR도 잘 봤습니다~! 
깔끔하게 잘 구현했네요.

2가지 생각해 볼 사항이 있습니다.
1. 회원이 닉네임이나 비밀번호를 수정할 때, 수정자 (lastModifiedBy) 가 회원의 닉네임이 입력되도록 기능을 추가해주어야 할 거 같아요!

2. 현재 컨트롤러 테스트에서 문서적인 차원에서 header 설정을 해주고 계신데, 실수로 header 설정을 하지 않아도 테스트가 통과할  거 같아요. 실수로 header 설정을 하지 않으면 테스트가 통과하지 못하도록 추가적인 설정을 해주어야 할 거 같아요.

**Comment by yeonise** [comment]
### Test Coverage Report
|Overall Project|94.51% **`-0.26%`**|:green_apple:|
|:-|:-|:-:|
|Files changed|98.35%|:green_apple:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[EmailDuplicateCheck.java](https://github.com/mujik-tigers/on-and-off/blob/8df09e3f445527faa4512db5aead77f4bedeab35/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fvalidator%2Fmember%2FEmailDuplicateCheck.java)|100%|:green_apple:|
|[NicknameDuplicateCheck.java](https://github.com/mujik-tigers/on-and-off/blob/8df09e3f445527faa4512db5aead77f4bedeab35/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fvalidator%2Fmember%2FNicknameDuplicateCheck.java)|100%|:green_apple:|
|[EmailFormatCheck.java](https://github.com/mujik-tigers/on-and-off/blob/8df09e3f445527faa4512db5aead77f4bedeab35/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fvalidator%2Fmember%2FEmailFormatCheck.java)|100%|:green_apple:|
|[PasswordFormatCheck.java](https://github.com/mujik-tigers/on-and-off/blob/8df09e3f445527faa4512db5aead77f4bedeab35/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fvalidator%2Fmember%2FPasswordFormatCheck.java)|100%|:green_apple:|
|[NicknameFormatCheck.java](https://github.com/mujik-tigers/on-and-off/blob/8df09e3f445527faa4512db5aead77f4bedeab35/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fvalidator%2Fmember%2FNicknameFormatCheck.java)|100%|:green_apple:|
|[PasswordMatchCheck.java](https://github.com/mujik-tigers/on-and-off/blob/8df09e3f445527faa4512db5aead77f4bedeab35/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fvalidator%2Fmember%2FPasswordMatchCheck.java)|100%|:green_apple:|
|[Member.java](https://github.com/mujik-tigers/on-and-off/blob/8df09e3f445527faa4512db5aead77f4bedeab35/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2FMember.java)|100%|:green_apple:|
|[ErrorType.java](https://github.com/mujik-tigers/on-and-off/blob/8df09e3f445527faa4512db5aead77f4bedeab35/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fexception%2FErrorType.java)|100%|:green_apple:|
|[WebConfig.java](https://github.com/mujik-tigers/on-and-off/blob/8df09e3f445527faa4512db5aead77f4bedeab35/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fconfig%2FWebConfig.java)|100%|:green_apple:|
|[MemberController.java](https://github.com/mujik-tigers/on-and-off/blob/8df09e3f445527faa4512db5aead77f4bedeab35/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fpresentation%2FMemberController.java)|100%|:green_apple:|
|[ResponseMessage.java](https://github.com/mujik-tigers/on-and-off/blob/8df09e3f445527faa4512db5aead77f4bedeab35/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Futil%2Fapi%2FResponseMessage.java)|100%|:green_apple:|
|[MemberService.java](https://github.com/mujik-tigers/on-and-off/blob/8df09e3f445527faa4512db5aead77f4bedeab35/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fapplication%2FMemberService.java)|100%|:green_apple:|
|[ModifiedMember.java](https://github.com/mujik-tigers/on-and-off/blob/8df09e3f445527faa4512db5aead77f4bedeab35/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fdto%2FModifiedMember.java)|100%|:green_apple:|
|[NicknameChangeForm.java](https://github.com/mujik-tigers/on-and-off/blob/8df09e3f445527faa4512db5aead77f4bedeab35/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fdto%2FNicknameChangeForm.java)|100%|:green_apple:|
|[ValidPasswordChangeForm.java](https://github.com/mujik-tigers/on-and-off/blob/8df09e3f445527faa4512db5aead77f4bedeab35/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fdto%2FValidPasswordChangeForm.java)|100%|:green_apple:|
|[PasswordChangeForm.java](https://github.com/mujik-tigers/on-and-off/blob/8df09e3f445527faa4512db5aead77f4bedeab35/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fdto%2FPasswordChangeForm.java)|100%|:green_apple:|
|[UniqueNicknameChangeForm.java](https://github.com/mujik-tigers/on-and-off/blob/8df09e3f445527faa4512db5aead77f4bedeab35/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fdto%2FUniqueNicknameChangeForm.java)|100%|:green_apple:|
|[MemberNotFoundException.java](https://github.com/mujik-tigers/on-and-off/blob/8df09e3f445527faa4512db5aead77f4bedeab35/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fexception%2Fmember%2FMemberNotFoundException.java)|0%|:x:|

**Comment by yeonise** [comment]
### Test Coverage Report
|Overall Project|94.51% **`-0.26%`**|:green_apple:|
|:-|:-|:-:|
|Files changed|98.35%|:green_apple:|
<br>

|File|Coverage||
|:-|:-|:-:|
|[EmailDuplicateCheck.java](https://github.com/mujik-tigers/on-and-off/blob/83ce5c18aafda2ab6797072a898972ea9b67d64e/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fvalidator%2Fmember%2FEmailDuplicateCheck.java)|100%|:green_apple:|
|[NicknameDuplicateCheck.java](https://github.com/mujik-tigers/on-and-off/blob/83ce5c18aafda2ab6797072a898972ea9b67d64e/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fvalidator%2Fmember%2FNicknameDuplicateCheck.java)|100%|:green_apple:|
|[EmailFormatCheck.java](https://github.com/mujik-tigers/on-and-off/blob/83ce5c18aafda2ab6797072a898972ea9b67d64e/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fvalidator%2Fmember%2FEmailFormatCheck.java)|100%|:green_apple:|
|[PasswordFormatCheck.java](https://github.com/mujik-tigers/on-and-off/blob/83ce5c18aafda2ab6797072a898972ea9b67d64e/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fvalidator%2Fmember%2FPasswordFormatCheck.java)|100%|:green_apple:|
|[NicknameFormatCheck.java](https://github.com/mujik-tigers/on-and-off/blob/83ce5c18aafda2ab6797072a898972ea9b67d64e/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fvalidator%2Fmember%2FNicknameFormatCheck.java)|100%|:green_apple:|
|[PasswordMatchCheck.java](https://github.com/mujik-tigers/on-and-off/blob/83ce5c18aafda2ab6797072a898972ea9b67d64e/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fvalidator%2Fmember%2FPasswordMatchCheck.java)|100%|:green_apple:|
|[Member.java](https://github.com/mujik-tigers/on-and-off/blob/83ce5c18aafda2ab6797072a898972ea9b67d64e/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2FMember.java)|100%|:green_apple:|
|[ErrorType.java](https://github.com/mujik-tigers/on-and-off/blob/83ce5c18aafda2ab6797072a898972ea9b67d64e/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fexception%2FErrorType.java)|100%|:green_apple:|
|[WebConfig.java](https://github.com/mujik-tigers/on-and-off/blob/83ce5c18aafda2ab6797072a898972ea9b67d64e/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fconfig%2FWebConfig.java)|100%|:green_apple:|
|[MemberController.java](https://github.com/mujik-tigers/on-and-off/blob/83ce5c18aafda2ab6797072a898972ea9b67d64e/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fpresentation%2FMemberController.java)|100%|:green_apple:|
|[ResponseMessage.java](https://github.com/mujik-tigers/on-and-off/blob/83ce5c18aafda2ab6797072a898972ea9b67d64e/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Futil%2Fapi%2FResponseMessage.java)|100%|:green_apple:|
|[MemberService.java](https://github.com/mujik-tigers/on-and-off/blob/83ce5c18aafda2ab6797072a898972ea9b67d64e/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fapplication%2FMemberService.java)|100%|:green_apple:|
|[ModifiedMember.java](https://github.com/mujik-tigers/on-and-off/blob/83ce5c18aafda2ab6797072a898972ea9b67d64e/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fdto%2FModifiedMember.java)|100%|:green_apple:|
|[NicknameChangeForm.java](https://github.com/mujik-tigers/on-and-off/blob/83ce5c18aafda2ab6797072a898972ea9b67d64e/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fdto%2FNicknameChangeForm.java)|100%|:green_apple:|
|[ValidPasswordChangeForm.java](https://github.com/mujik-tigers/on-and-off/blob/83ce5c18aafda2ab6797072a898972ea9b67d64e/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fdto%2FValidPasswordChangeForm.java)|100%|:green_apple:|
|[PasswordChangeForm.java](https://github.com/mujik-tigers/on-and-off/blob/83ce5c18aafda2ab6797072a898972ea9b67d64e/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fdto%2FPasswordChangeForm.java)|100%|:green_apple:|
|[UniqueNicknameChangeForm.java](https://github.com/mujik-tigers/on-and-off/blob/83ce5c18aafda2ab6797072a898972ea9b67d64e/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fmember%2Fdto%2FUniqueNicknameChangeForm.java)|100%|:green_apple:|
|[MemberNotFoundException.java](https://github.com/mujik-tigers/on-and-off/blob/83ce5c18aafda2ab6797072a898972ea9b67d64e/src%2Fmain%2Fjava%2Fsite%2Fonandoff%2Fexception%2Fmember%2FMemberNotFoundException.java)|0%|:x:|

**Pull request merged**
